name: "Frontend"

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build_frontend:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
          npm run build