name: "Pull actions"

on:
  pull_request:
    branches:
      - master

jobs:
  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
