name: "Push actions"

on:
  push:
    branches:
      - master

jobs:
  build_frontend:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  cut_release:
    runs-on: ubuntu-latest
    name: Cut Github release
    needs: build_frontend
    steps:
      - name: Install dependencies
        run: |
        python3 -m pip install -U setuptools wheel
          python3 -m pip install -U reporeleaser
      - name: Crete release
        run: reporeleaser --test --token ${{ secrets.GITHUB_TOKEN }} --repo reporeleaser --release $(date "+%Y%m%d%H%M%S") --hide_footer
