name: "Push actions"

on:
  push:
    branches:
      - master

jobs:
  build_frontend:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  cut_release:
    runs-on: ubuntu-latest
    name: Create a new GitHub release
    needs: build_frontend
    steps:
      - name: Install dependencies
        run: |
          pip3 install -U setuptools wheel
          git clone https://github.com/ludeeus/reporeleaser.git
          cd reporeleaser
          python3 setup.py development
      - name: Crete release
        run: reporeleaser --test --token ${{ secrets.GITHUB_TOKEN }} --repo hacs/frontend --release $(date "+%Y%m%d%H%M%S") --hide_footer
